### ISSUE TITLE
Missing --session-name option support for credential-process

### ISSUE THREAD

**Issue by zhixueli** [aws/rolesanywhere-credential-helper#19]
When using aws_signing_helper tool to obtain temporary credentials with credential_process, it's needed to have a friend session name to identify the API calls with the temp credentials in CloudTrail.

**Comment by 13ajay** [comment]
Currently, the hex-encoded serial number of the signing certificate is used as the session name when assuming the customer role. Is this sufficient for your use case?

**Comment by zhixueli** [comment]
I've noticed hex-encoded serial number, but this is not friendly for customer, it will be great if customized session name can be used.

**Comment by reverson** [comment]
I see this was release 5 days ago, but the binary in the release doesn't seem to have this option.  Furthermore, once I build from source, I'm able to include the option, but I get the following error 
```
AccessDeniedException: Not authorized to set roleSessionName.
```

**Comment by 13ajay** [comment]
> I see this was release 5 days ago, but the binary in the release doesn't seem to have this option.

Thank you for bringing this to our attention. There has been an update now, so the option should work, but please let us know if you run into issues.
