### ISSUE TITLE
Provide option for caching credentials.

### ISSUE THREAD

**Issue by jon-armen** [aws/rolesanywhere-credential-helper#31]
When used in combination with https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html as directed by https://docs.aws.amazon.com/rolesanywhere/latest/userguide/credential-helper.html, each request thru the aws cli or sdk will obtain it's own session.  When using external credentials, those credentials must be implemented in the external process.

In our example, we are using the SDK to run tests in parallel.  Those tests utilize the AWS SDK and operate in a multithreaded pattern.  We easily exceed the default CreateSession threashold of 10/sec.  While we can authenticate once, and then store the credentials ourselves, it would be ideal if this tool could handle that internally.

**Comment by benkehoe** [comment]
Just checking here, do you use `serve`? The credential process can't/shouldn't cache credentials, but when running as an IMDSv2 endpoint I agree it definitely should be caching the credentials

**Comment by 13ajay** [comment]
You can also use `update`, but temporary credentials would be cached to the AWS `credentials` file in that case. 

Closing for now, but feel free to reopen if you have further questions or run into issues.

**Comment by ibexa-yuna** [comment]
Hi, what are those tools `serve` and `update`? Or those are references to CLI commands?

**Comment by medoni** [comment]
Any update on this?

I run in the same issue when using RolesAnywhere in CI/CD Pipeline with terraform.

```yaml
- script: |
    mkdir -p ~/.aws
    cat >~/.aws/config <<EOF 
    [default]
    credential_process = aws_signing_helper credential-process --certificate ... --private-key ... --trust-anchor-arn ... --profile-arn ... --role-arn ...
    region = eu-central-1
    output = json
    EOF
  displayName: 'Configure aws'
```

And I got this error when multiple pipelines run parallel:

```
Planning failed. Terraform encountered an error while generating this plan.
╷
│ Error: No valid credential sources found
│ 
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on provider.tf line 2, in provider "aws":
│    2: provider "aws" {
│ 
│ Please see https://registry.terraform.io/providers/hashicorp/aws
│ for more information about providing credentials.
│ 
│ Error: failed to refresh cached credentials, process provider error:
│ credential process timed out: signal: killed
│ 
╵

```

I'm using the version 1.5.0 of aws_signing_helper

**Comment by 13ajay** [comment]
Are things working when you run a single execution in a single pipeline? If not, maybe there's something wrong with the way in which you wrote your Terraform or configured the credential helper in that environment. 

The original question asked here is about caching credentials so that `CreateSession` isn't called unnecessarily, so your question seems to be slightly different. AFAIK, there shouldn't be any issues when running the the credential helper with the credential process command as long as it's configured properly. If it's timing out, maybe there's a network connectivity issue in your environment.
