### ISSUE TITLE
Release for linux arm64 based architecture

### ISSUE THREAD

**Issue by clementrey-dev** [aws/rolesanywhere-credential-helper#35]
Hello,

We are currently using  this helper from raspberry pi 4 device. For now, we are building our self the binaries but it would really help if arm64 for linux (debian) binaries would be released as well.

Do you have plan to release them in the future ?

Best Regards

**Comment by 13ajay** [comment]
ARM64 binaries are now available on [this page](https://docs.aws.amazon.com/rolesanywhere/latest/userguide/credential-helper.html) for Linux and MacOS. Please let us know if there are any issues. Thanks.
