### ISSUE TITLE
Windows "Local Computer" Cert Store Support

### ISSUE THREAD

**Issue by jake6532** [aws/rolesanywhere-credential-helper#41]
Would it be possible to allow the searching of certificates for windows from the local computer cert store as well?  Similar to Instance profiles in AWS it would be nice to maintain certificates/role permissions at the server level instead of having to worry about what user is executing it.

**Comment by wcoleman** [comment]
We would also really like this feature. I was disappointed to see that the certificate store only had local user certificate store support. We will be using IAM roles anywhere from websites run in IIS on prem to access AWS resources. Using the local computer cert store would make this possible.

**Comment by 13ajay** [comment]
Thanks for raising this issue. We will look into implementing this soon.

**Comment by 13ajay** [comment]
The linked PR has been merged, so I'll close this issue. Please let us know if you face further problems with this.
