### ISSUE TITLE
How to properly debug "Some attributes failed to be mapped into session tags" error?

### ISSUE THREAD

**Issue by gcavalcante8808** [aws/rolesanywhere-credential-helper#77]
Hello Folks!

I'm try to test the AWS Roles anywhere, but I'm receiving the following error:

```
2024/06/30 03:48:56 AccessDeniedException: Unable to assume role for arn:aws:iam::000000000000:role/local-vault. Some attributes failed to be mapped into session tags. Issuer: [  ]; Subject: [  ]; SAN: [ DNS/2 ]
```

Based on https://docs.aws.amazon.com/pt_br/rolesanywhere/latest/userguide/workload-identities.html I've also tried to check my client certificate attrs using openssl:

```bash
root@vault:/etc/ssl# openssl x509 -noout -issuer -in host.pem 
issuer=C = BR, ST = Brazil, L = SaoPaulo, O = Dev Environments, OU = Sidecloud Vault Root CA, CN = Sidecloud Local Vault CA
root@vault:/etc/ssl# openssl x509 -noout -subject -in host.pem 
subject=CN = abdalla
```

Btw my profile is using the default attribute mapping configuration:
![image](https://github.com/aws/rolesanywhere-credential-helper/assets/640897/cae6de47-5990-4abc-a39d-f3610f1e19aa)

And I can see my requests on the console:
![image](https://github.com/aws/rolesanywhere-credential-helper/assets/640897/cdefd59b-9e71-493a-a04f-186c84c116f3)

I tried with versions 1.1.0 and 1.0.6 on Linux and both returns the error.

Can you folks point me to some method to debug or details why it is not working?

> I plan to test SPIFFE formats next, but I 'd like to at least make this simple test pass before proceeding.

Thanks in advance!

**Comment by gcavalcante8808** [comment]
Well, whatever was the error, by recreating the CA and certificates using the default CFSSL worked for me this time.

**Comment by adkafka** [comment]
Given that this is the only thread on the internet that seems to reference the "Some attributes failed to be mapped into session tags" issue, I thought I'd add my findings here.

I learned that there are extra restrictions on certificate format if you want to use the certificate metadata in session tags. For example, I had a root CA with parentheses in the CN name and that resulted in the following error:

```
Error generating credentials: operation error RolesAnywhere: CreateSession, https response error StatusCode: 403, RequestID: REDACTED, AccessDeniedException: Unable to assume role for arn:aws:iam::REDACTED:role/REDACTED. Some attributes failed to be mapped into session tags. Issuer: [  ]; Subject: [ CN ]; SAN: [  ]
```

After going through AWS support, I was able to confirm that is not supported. The link to docs I got was: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_tags.html#id_tags_rules

> Character requirements – Tag keys and values can include any combination of letters, numbers, spaces, and _ . : / = + - @ symbols.

I requested the IAM Roles Anywhere docs be updated to reflect this limitation.
